gatsby-node.js
src/cms/cms.js
src/cms/preview-templates/CustomPagePreview.js
src/components/Footer.js
src/components/Layout.js
src/components/LiveEventWidgetComponent.js
src/components/LogoutButton.js
src/components/Navbar.js
src/components/ScheduleLiteComponent.js
src/components/SpeakersWidgetComponent.js
src/content/footer.json
src/content/navbar.json
src/pages/custom-pages/about-event.md
src/pages/custom-pages/contact.md
src/pages/custom-pages/help.md
src/pages/custom-pages/past-events.md
src/pages/custom-pages/who-we-are.md
src/styles/footer.module.scss
src/styles/navbar.module.scss
src/templates/custom-page.js
static/admin/config.yml

New custom pages through CMS, footer and navbar configuration

Navbar footer cms

---

src/actions/summit-actions.js
src/components/ScheduleLiteComponent.js
src/pages/a.js
src/reducers/summit-reducer.js
src/routes/ShowTimeRoute.js
src/templates/marketing-page.js
src/templates/schedule-page.js

Marketing site available for logged users if the summit hasn't started yet. Private routes redirects to marketing site

updating marketing site redirects

---

src/components/Countdown.js
src/styles/countdown.module.scss
src/templates/marketing-page.js

Adds the new countdown component for marketing site

countdown component

---

package.json

updating chat

---

src/components/MarketingHeroComponent.js
src/routes/PrivateRoute.js

Marketing hero countdown

---

package.json
src/actions/clock-actions.js
src/actions/summit-actions.js
src/components/ClockComponent.js
src/components/Layout.js
src/components/MarketingHeroComponent.js
src/components/TalkComponent.js
src/reducers/clock-reducer.js
src/reducers/summit-reducer.js
src/state/ReduxWrapper.js
src/templates/event-page.js
src/templates/marketing-page.js
src/templates/schedule-page.js
src/utils/phasesUtils.js
yarn.lock

New reducer to manage phases of summit and events. Improved UX

Clock reducer

---

package.json
yarn.lock

schedule lite - details

---

src/routes/PrivateRoute.js
src/utils/authorizedGroups.js

authorized users with no badge can access session events

---

src/templates/event-page.js

Refactor of event page

---

src/components/MarketingHeroComponent.js

FIX: button wrapped on an anchor and general code tweaks due to warnings

FIX: button wrapped on an anchor and general code tweaks due to warnings

---

src/actions/user-actions.js

Badge scanned success message was changed

---

src/utils/authorizedGroups.js

fix on buggy condition on isAuthorizedBadge

Fix on access show

---

src/templates/sponsor-page.js

Fixed error when sponsors object has no sponsors

---

src/actions/user-actions.js
src/styles/extra-questions.module.scss
src/templates/extra-questions-page.js

* show attendee information
* display text input if there's something missing
* updates the ticket with the attendee data
* validates that the attendee data is completed before save

Adds attendee information on extra questions page

---

gatsby-config.js
src/styles/bulma.scss
src/styles/fonts.scss
src/styles/style.scss

Changes the font family from "Nunito Sans" to "Roboto"

replacing font family

---

src/routes/PrivateRoute.js

* Fix on checking crendentials message
* Refactoring

Updated Private Route

---

src/components/AttendeeToAttendeeWidgetComponent.js

if user is an admin can CHAT no matter what

Updated A2A permissions

---

src/components/AttendeeToAttendeeWidgetComponent.js

* Updated A2A permissions
if user is an admin can CHAT no matter what
* Refactoring

Updated A2A permissions (#87)

---

package.json
yarn.lock

Updated registration lite version

---

src/reducers/clock-reducer.js
src/reducers/event-reducer.js
src/reducers/summit-reducer.js

Added SYNC_DATA actions to following reducers

---

src/reducers/my-schedule-reducer.js
src/reducers/schedule-reducer.js

new filters are the source of truth bc
they could have new keys or less keys that current one

Fixed Synch data for filter

---

package.json
src/state/store.js
yarn.lock

Updated redixux-persist storage

---

src/actions/clock-actions.js
src/components/NoTalkComponent.js
src/templates/event-page.js

summit event phases refactoring
task #2628767

Summit Event page update

---

src/components/HeroComponent.js
src/pages/a.js
src/routes/ShowOpenRoute.js
src/routes/WithBadgeRoute.js
src/routes/WithTicketRoute.js

Fix on routing

---

package.json
yarn.lock

New A2A widget reference w/error boundaries

New A2A widget reference w/error boundaries

---

src/components/AttendeeToAttendeeWidgetComponent.js

Fix related to 
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2626115&fileview=grid

Tracking bypass when user profile information is not complete

---

static/admin/config.yml

* Fix the CMS config for the widgets on the sponsor page

fixing cms widgets for sponsor page

---

package.json
yarn.lock

This commit references to the new version of a2a where duplicate messages issue in conversation threads were fixed

update stream-chat package to avoid duplication error

---

package.json
yarn.lock

This commit fix the error reported in https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2635185&fileview=grid

a2a widget session loss error

---

src/routes/authorization-callback-route.js
src/styles/full-profile.module.scss
src/templates/full-profile-page.js

* Fix the error after the redirect when the user didn't accept the permissions on the post login screen
* Adjust dropdowns on full profile page
None
None

Cancelling permission fix

---

gatsby-node.js

if the setting does not came from marketing api
but it does exists on json file
should be turned off
related to https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2633015

Fixed initial filters settings loading

---

src/reducers/my-schedule-reducer.js
src/reducers/schedule-reducer.js
src/templates/my-schedule-page.js
src/templates/schedule-page.js
src/utils/filterUtils.js

ref https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2631632

Fixed resynch for filter settings

---

gatsby-node.js

Fixed initial values on schedule filter

---

package.json
yarn.lock

PR regarding this tix: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2638725&fileview=grid

A2A - touch behavior changes on mobile

---

src/templates/event-page.js

Fixed main event not loading

---

package.json
src/components/AttendeeToAttendeeWidgetComponent.js
yarn.lock

Related tasks:
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2638716&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2642516&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2635185&fileview=grid

a2a widget fixes and tweaks

---

src/templates/full-profile-page.js

fixed persist error on checkboxes values
* show email
* show full name

Full Profile checkboxes

---

src/templates/full-profile-page.js

added new checkbox 'Allow chat with me'
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2638711&fileview=grid

Updated full profile

---

package.json
yarn.lock

Related tasks:
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2637668&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2626416&fileview=grid

a2a fixes & improvements

---

package.json
yarn.lock

Related tasks:
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2633618&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2638710&fileview=grid

reference to a2a widget new version

---

src/styles/lobby-hero.module.scss

* changes the flex direction for the buttons on mobile 
Ticket: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2640779&fileview=grid
No
Nothing

Change flex direction on mobile for buttons

---

src/actions/user-actions.js
src/components/RegistrationLiteComponent.js

* If the user uses different data when buying a ticket through reg-lite, and the purchase is successfull, it updates the profile data

updates profile with diff data from reg-lite

---

package.json
yarn.lock

Related tasks:
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2637667&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2644283&fileview=grid

suspend auto room creation + chatme & emailme restriction hint

---

package.json
src/actions/schedule-actions.js
yarn.lock

https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2631632&fileview=grid

fix company filter

---

src/actions/event-actions.js
src/reducers/schedule-reducer.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2646342&fileview=grid

Fixed duplicated events on schedule

---

package.json
yarn.lock

Fixed my schedule
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2646382&fileview=grid

Updated Lite schedule

---

src/templates/full-profile-page.js

Fix on allow chat with me option
ref https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2638710

Full Profile page

---

package.json

fixed data issue with level
ref https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2649211

Updated Filter widget version

---

src/components/SponsorComponent.js
static/admin/config.yml

Related task:
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2650031&fileview=grid

Add new field to sponsor admin schema & "show logo" flag validation

---

src/styles/lobby-hero.module.scss

* Removes the fixed height for mobile header at lobby
None
None
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2640779

Fix mobile header for Lobby

---

package.json
yarn.lock

Related tasks:
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2642342&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2651400&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2651390&fileview=grid

Requested a2a fixes and changes

---

src/components/MarketingHeroComponent.js
src/styles/lobby-hero.module.scss

* Adjust the text on the right column to mantain the text inside the column
None
None
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2631652

Adjusting text in left column

---

src/components/ExtraQuestions.js
src/styles/extra-questions.module.scss
src/templates/extra-questions-page.js

* Display the disclaimer and the checkbox extra questions in the same way as in registration summit
None
None
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2650311

Adjusting styles for extra questions page

---

package.json
src/components/FilterButton/index.module.scss
src/styles/full-schedule.module.scss
yarn.lock

https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2658525&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2658573&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2609501&fileview=grid

Full Schedule styles fixes

---

package.json
yarn.lock

Related tasks:
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2651400&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2656342&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2642342&fileview=grid
All changes and fixes were made in a2a widget

a2a unread messages badge + ui tweaks

---

package.json
yarn.lock

Relate tasks:
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2656346&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2645448&fileview=grid

A2A new filter scope selector & ui tweaks

---

src/components/Navbar.js
src/templates/marketing-page.js

https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2633045&fileview=grid

fix navbar

---

src/templates/event-page.js

https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2628767&fileview=grid

Allow events with VOD

---

src/routes/WithAuthRoute.js
src/utils/authorizedGroups.js

Add check on badge access level VIRTUAL
https://tipit.avaza.com/project/view/232086#!tab=task-pane&groupby=ProjectSection&view=vertical&task=2670723&fileview=grid

Check on access level VIRTUAL

---

package.json
yarn.lock

fix speaker tooltip to show beneath site header
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2627449&fileview=grid

update live widget

---

src/routes/WithAuthRoute.js
src/templates/my-schedule-page.js
src/templates/schedule-page.js
src/templates/ticket-error-page.js

updated logic when user has no virtual access to the event
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2670723&fileview=grid

Refactored non virtual authz

---

package.json
yarn.lock

Related tasks:
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2665068&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2670961&fileview=grid

live testing review

---

gatsby-browser.js
src/components/LiteScheduleComponent.js
src/reducers/schedule-reducer.js
src/templates/schedule-page.js
src/utils/envVariables.js
src/utils/schedule.js

https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2673296&fileview=grid

allow filtering schedule events by tag

---

src/components/AttendeeToAttendeeWidgetComponent.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2687515&fileview=grid

FIX: get all possible profile info from idpProfile

---

package.json
yarn.lock

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2689173&fileview=grid

a2a badges alignment

---

gatsby-browser.js
src/utils/envVariables.js

fixed undefined setting
ref https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2673296

Fix on env variables

---

src/components/LiveEventWidgetComponent.js
src/styles/style.scss

https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2694953&fileview=grid
https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2694948&fileview=grid

fix padding

---

src/templates/home-page.js

Sets onlyPresentations to true in live event widget.

---

src/components/UpcomingEventsComponent.js
src/templates/home-page.js

set showAllEvents to false ( before true )
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2696654&fileview=grid

Updated upcomming events widget config at lobby page

---

package.json
yarn.lock

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2696634&fileview=grid

Help Desk missing profile image

---

package.json
yarn.lock

ref https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2696792

remove is-rounded attribute from badge images

---

src/components/UpcomingEventsComponent.js
src/templates/home-page.js

showAllEvents set to true
ref https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2696654

Update upcommingevents config

---

package.json
yarn.lock

ref
https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2696595
and
https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2700268

updated full schedule version

---

src/routes/WithAuthRoute.js

Fixed auth route race condition

---

package.json
yarn.lock

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2701242&fileview=grid

A2A - set Private as fullname when user name is null

---

package.json
src/state/store.js
yarn.lock

removed localforage due safari issue with db indexed

Removed localforage

---

gatsby-browser.js
gatsby-ssr.js
package.json
src/state/ReduxWrapper.js
src/state/store.js
yarn.lock

* Removed IndexedDB storage ( due incompatibilities with Safari)
* Reintroduced local storage and removed data that is not necesary to store
* upgraded redux-persist library
ref https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2706991

Local Storage Refactor

---

package.json
yarn.lock

Registration lite was not expanding correctly all tickets fields
( badge, badge type, badge type features / badge type access levels)
ref
https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2714170

Fix on first time access using registration lite

---

src/styles/advertise.module.scss

* Removes the limitation of width for high resolutions screens (2k, 4k)
* Forces the image of the first ad to use the 100% of the width
No
Nothing
ref: https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2700126

fixes issue with ads on high resolutions

---

src/templates/extra-questions-page.js

* Changes the text on the extra questions page
No
Nothing
ref: https://tipit.avaza.com/project/view/293733#!tab=task-pane&task=2723599

Change copy text on extra questions page

---

src/templates/extra-questions-page.js

* Hides the checkbox for the disclaimer if there's no disclaimer
No
Nothing
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2709741&fileview=grid

hide disclaimer if there's no content

---

package.json
yarn.lock

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2711915&fileview=grid

attendees widget w supabase model refactor and performance optimizations

---

package.json
yarn.lock

ref https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2711915

attendees list population refactor

---

package.json
yarn.lock

ref https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2711915

a2a signup patch

---

src/components/NoTalkComponent.js

* Replaces the format for days on the event page when the event isn't started yet.
No
Nothing
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2738030

Replace ordinal number with cardinal in event dates

---

src/components/Footer.js

Use javascript to dynamically set the year for the copyright

Footer dynamic copyright

---

package.json
yarn.lock

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2701241&fileview=grid
Signed-off-by: Román Gutierrez <roman.gutierrez@gmail.com>

integrate new a2a widget version w/local filter feature

---

static/admin/config.yml

* Fix the Config file of the CMS
No
Nothing
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2723468&fileview=grid

Fixing typo on CMS config for favicon

---

src/components/MarketingHeroComponent.js
src/styles/bulma.scss
src/styles/fonts.scss
src/styles/lobby-hero.module.scss
src/styles/style.scss

* Applyes the Yahoo Sans font to the site
No
Nothing
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2756753&fileview=grid

Applying yahoo font to fnvirtual site

---

src/components/LoginButton.js
src/components/MarketingHeroComponent.js
src/templates/token-expire-page.js

* Uses Okta for login on yahoo site
No
Nothing
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2782319

Using okta for login

---

src/routes/ShowOpenRoute.js

ref https://tipit.avaza.com/project/view/295592#!tab=task-pane&task=2783578

Updated no show time message

---

src/components/MarketingHeroComponent.js
src/styles/lobby-hero.module.scss

* Changes the shape of the login button
No
Nothing
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2756754&fileview=grid

change shape of login button

---

src/components/LobbyHeroComponent.js

* Removes the black diagonal bar on the home header.
No
Nothing
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2788063&fileview=grid

Removing diagonal from lobby header

---

src/actions/base-actions.js
src/components/RegistrationLiteComponent.js

* Fix a bug when the modal of registration lite widget it's empty
No
Nothing
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2790263&fileview=grid

Alert on api error for providers

---

package.json
yarn.lock

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2725815&fileview=grid
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2698241&fileview=grid

new help icon & fix: attendee doesnt show when fullname is null or empty

---

src/components/AttendeeToAttendeeWidgetComponent.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2790647&fileview=grid
Signed-off-by: romanetar <roman.gutierrez@gmail.com>

protect signout tracker ref

---

package.json
yarn.lock

ref https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2698241
Signed-off-by: romanetar <roman.gutierrez@gmail.com>

fix getting agent info over new model

---

src/styles/lobby-hero.module.scss

* Removes the border on the login button at marketing page
No
Nothing
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2805397

Removing border from login button

---

src/components/ProfilePopupComponent.js
src/styles/profile.module.scss

* Mark the field `first_name`at profile popup as read only
* Changes the cursor on read only fields to improve UX
No
Nothing
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2810312

Make first name field read only. Cursor css

---

package.json
yarn.lock

ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2676139&fileview=grid
Signed-off-by: romanetar <roman.gutierrez@gmail.com>

fix some attendees dont get listed

---

package.json
src/components/poster-card/index.jsx
src/components/poster-card/index.module.scss
src/components/poster-card/vote-button.js
src/components/poster-card/vote-button.module.scss
yarn.lock

```
import PosterCard from '../components/poster-card'
<PosterCard
title=‘Poster title here’
order(?)=“#12345”
track(?)={{name: ‘track’, color: ‘purple’}}
imageURL(?)=‘https://i.ibb.co/4PsXhXW/88-Techpulse-Paper-88-What-s-in-a-name-Poster.jpg’
onDetailClick(?)={()=> this.onDetailClick()}
isVoted={isVoted}
addVote(?)={canVote ? () => this.addVote() : null}
removeVote={() => this.removeVote()}
/>
```

Adds PosterCard presentational component.

---

package.json
src/components/VideoComponent.js
src/components/VimeoPlayer.js
src/components/VimeoPlayerEventNames.js
src/styles/video.module.scss
yarn.lock

check if the provided url has a "vimeo" format
and display an embeded player using Vimeo Player API.
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2809533&fileview=grid

Added Vimeo Player

---

src/actions/user-actions.js
src/components/poster-card/vote-button.js
src/reducers/user-reducer.js

Disallows casting votes when already voting.

Improves poster vote button UX.

---

src/actions/presentation-actions.js
src/templates/poster-detail-page.js

fixed wrong indirection
ref https://tipit.avaza.com/project/view/295592#!tab=task-pane&task=2833365

Fixed Poster details Authz

---

src/components/page-header/index.module.scss

Fixes issue when uploading image asset at 2x.

Sets poster page header component image max height to header max height.

---

package.json
src/components/AttendeeToAttendeeWidgetComponent.js
yarn.lock

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2826479&fileview=grid

parameterized filter scope selector

---

src/actions/presentation-actions.js

Fixes failing to calculate votes count.

References correct property votes attendee property.

---

src/components/poster-header-filter/index.jsx
src/reducers/presentations-reducer.js
src/templates/posters-page.js

There was an integration issue with posters header filters component and filters widget.
One evident behavior this caused was that if My Votes filter was activated before or while data refresh happened, data refresh overrode My Votes filtering.
This PR fixes that.

Better integrates posters header filters with filters widget filtering.

---

package.json
src/components/SpeakersWidgetComponent.js
yarn.lock

updates speakers widget to latest version 
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2836075&fileview=grid

Updated featured speakers widget

---

package.json
yarn.lock

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2844578&fileview=grid
ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2826479&fileview=grid

rooms ordered by age & filter scope fix

---

src/actions/event-actions.js
src/reducers/event-reducer.js
src/routes/WithBadgeRoute.js
src/templates/event-page.js

* now first its provided the data on the reducer and in background is
retrieved fresh data from api
ref 
https://tipit.avaza.com/project/view/295592#!tab=task-pane&task=2837819

Updated strategy to retrieve activity data on activity detail page

---

src/actions/schedule-actions.js
src/reducers/all-schedules-reducer.js
src/reducers/clock-reducer.js
src/reducers/event-reducer.js
src/reducers/presentations-reducer.js
src/reducers/schedule-reducer.js
src/templates/event-page.js
src/templates/schedule-page.js
src/utils/phasesUtils.js

* refactored reducers to load initial data on default state
( when it's possible and its not a direct dependency of current store state)
* refactored schedule reducer to be able to reload schedule state on page reload
ref https://tipit.avaza.com/project/view/295592#!tab=task-pane&task=2846562

Fixed DataSync issue

---

package.json
yarn.lock

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2848054&fileview=grid
no breaking changes

A2A realtime resubscription + filter scope tweaks

---

src/components/PosterLiveSession.js

Ref: https://tipit.avaza.com/project/view/295592#!tab=task-pane&groupby=ProjectSection&view=vertical&task=2849224&fileview=grid

If provided meeting url is an external one, opens url in new tab.

---

src/components/PosterButton.js
src/components/poster-card/index.jsx
src/styles/poster-components.module.scss

This PR make posters zoom larger when clicking on poster card view detail or view poster detail button in poster detail page.

Make posters zoom larger.

---

src/components/poster-grid/index.jsx

Causes poster card rendering on mobile.

Removes special poster grid formatting when poster count is 3.

---

src/components/Layout.js

**What's broken**
Each page should have one main landmark.
Changed markup for `#content-wrapper` to `<main>`.

Added proper markup to content wrapper.

---

src/components/PosterLiveSession.js

This one cleans up markup and copy as it should be in main branch.

Changes Poster Live Session component markup and copy.

---

src/components/poster-card/index.jsx
src/components/poster-card/index.module.scss

This is a fix for keyboard users as they could not open the other posters when exclusively using keyboard navigation.
An accessibility fix.
No
None!

Converted the heading 2 links to links.

---

src/templates/posters-page.js

Ref: https://tipit.avaza.com/project/view/295592#!tab=task-pane&groupby=ProjectSection&view=vertical&task=2850725&fileview=grid

Sets page settings on track group id change.

---

package.json
yarn.lock

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2852321&fileview=grid
no breaking changes

large company title breaks attendee item layout

---

src/styles/sponsor-page.module.scss

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2850909&fileview=grid

ul bullets aren't showing in sponsor page intro section

---

src/templates/custom-page.js

Pages must have one `<h1>` heading for title page.
Markup update for custom page template.
No.
No documentation needed.

Replace H2 tag for main heading in custom page template.

---

src/reducers/presentations-reducer.js
src/reducers/schedule-reducer.js

first update the state then filter the events

Fixed filter reducer logic

---

package.json
yarn.lock

* popup position on calendar view mode
* null location fix

Updated full schedule widget version

---

src/templates/full-profile-page.js

Easier to understand with a screen reader.
Markup
No
NA

Added label for the bio and SoI text inputs under edit profile

---

src/components/ProfilePopupComponent.js
src/templates/full-profile-page.js

Easier to understand with screen reader
Markup
No
NA

Added label for zoom slider in edit profile popup

---

src/components/ProfilePopupComponent.js

Easier to navigate with screenreader
Markup changes
No
NA

Converted Edit Profile Popup to use a Heading level 2

---

src/templates/full-profile-page.js

Easier to navigate with screen reader
Markup
No
NA

Converted the div to a Heading Level 2 for schedule on Profile Page

---

src/content/home-settings.json

Fixes the data structure of the image header on home-settings.json file
No
Nothing
ref: https://tipit.avaza.com/project/view/305538#!tab=task-pane&task=2870727

Fix structure of home-settings json

---

src/content/home-settings.json

Fixes the data structure of the image header on home-settings.json file
No
Nothing
ref: https://tipit.avaza.com/project/view/305538#!tab=task-pane&task=2870727

Fixing home-settings.json structure

---

src/actions/schedule-actions.js

https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2861137&fileview=grid

Fix share link on scheudle

---

src/utils/schedule.js

https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2878807&fileview=grid

Fix Abstract filter

---

src/templates/home-page.js

* Change text in left column on home page
No
Nothing
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2884431&fileview=grid

Change title for home page

---

package.json
yarn.lock

ref https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2854613

updated registration lite widget version

---

src/components/VimeoPlayer.js
src/templates/event-page.js

https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2888987

Move autoplay logic to event video url

---

package.json
yarn.lock

fixed today speakers method
ref https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2897665

Updated speakers widget version

---

src/actions/user-actions.js
src/components/RegistrationLiteComponent.js

* Adds a try catch block on the closeWidget function
No
Nothing
ref: https://tipit.avaza.com/project/view/304272#!tab=task-pane&task=2854613

Adding try catch block on closeWidget function

---

src/utils/masonry.js

* Fixes the function to determine if a dummy image is required 
No
Nothing
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2640774&fileview=grid

Change masonry format function

---

src/pages/custom-pages/educational-videos.md
src/styles/style.scss

* Style changes in educational videos page
No
Nothing
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2942347

[CUSTOM] Add styles to educational videos page

---

package.json
src/components/Content.js
src/pages/custom-pages/educational-videos.md
src/styles/navbar.module.scss
src/styles/style.scss
yarn.lock

* Changes styles in starsfest22 site
No
Nothing
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2942347&fileview=grid

Adjusting styles for vimeo and navbar

---

src/templates/marketing-page.js

* Fixing mobile image on marketing page
No
Nothing
ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=2956288&fileview=grid

[CUSTOM] Adjusting property name for mobile image

---

src/pages/custom-pages/stars-toolkit.md
src/styles/custom-pages.scss
src/templates/custom-page.js

* Adjusting styles to keep images on a similar size
* Adds a right padding to right side on desktop size
No
Nothing
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2962249

[CUSTOM] New styles for images and page

---

src/content/sponsors-tiers.json
src/reducers/sponsor-reducer.js
src/templates/expo-hall-page.js
static/admin/config.yml

* Change props names and add missing props to expo hall page on template and CMS
No
Nothing
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2977450

[CUSTOM] Refactor expohall page and fix cms
