src/templates/sponsor-page.js

this bug was introduced when we removed the side Image for this page here: https://github.com/fntechgit/virtualevent-poc/commit/10bd64135e4b359a2d111f6c0176ac84b254e7ca

remove double header in sponsor page

---

src/routes/ShowOpenRoute.js

ref https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskDueDate&view=vertical&task=2694574&fileview=grid

FIX: avoid showopenroute renders before summit_phase initialization

---

src/styles/style.scss

Reverts margin top change introduced in #183

Removes margin top to live event widget container.

---

src/routes/authorization-callback-route.js

To fix navigation issue after idp callback.

Uses gatsby navigate instead of reach router's navigate.

---

src/components/MarketingHeroComponent.js
src/components/RegistrationLiteComponent.js

* Disable the reg-lite widget for summits that are invite only
No
* Summits that are invite-only would not load the reg-lite widget
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2780784

Disable reg-lite for invite only events

---

gatsby-browser.js
package.json
src/styles/style.scss
yarn.lock

**What's broken**
Whe user navigates the page using keyboard (e.g. tabbing accross links), we must show an indicator of the focused element. This indicator is currently missing on the page.
We added a module that detects when user interacts using a keyboard to show a focus indicator that's not shown when user interacts using a mouse or touch screen.
`yarn install` is needed in order to add the new dependency.

Added focus indicator to links and buttons for keyboard navigation

---

src/reducers/presentations-reducer.js
src/templates/poster-detail-page.js

* Fixes the double call on detail page navigation
* Fix the duplicate presentation on the widget with the current detailed presentation
No
Nothing
ref: https://tipit.avaza.com/project/view/295592#!tab=task-pane&task=2835300

Fixing double load for recommended presentations

---

src/utils/phasesUtils.js

If no start date and no end date set for track group voting period, set its phase to during.

Fix voting period phase calculation

---

src/utils/phasesUtils.js

If summit or event start date == now or summit or event end date == now, phase calculation was being changed to null.
Thus, changing state from BEFORE to null then to DURING, or from DURING to null then to AFTER.
This could lead to some component flickering.
This hotfix fixes summit and event phase calculation.

Fixes summit and event phase calculation.

---

src/components/ProfilePopupComponent.js

**What's broken**
When clicking the profile picture button, a profile modal is opened but focus remains on the pp button. 
When navigating inside the modal (tab / shift + tab) focus would leave the scope and start focusing elements outside the modal.
Autofocusing the header <p> when opening the modal. Limiting the focus to a circular navigation inside the desired scope, until the modal is closed.
This PR doesn't introduce any breaking change.

ProfilePopupComponent: focus is now scoped to modal until closed

---

src/components/poster-card/index.module.scss

Fixes [In the poster gallery, not every poster has the number identified under the title](https://tipit.avaza.com/project/view/295592#!tab=task-pane&groupby=ProjectSection&view=vertical&task=2846020&fileview=grid) Avaza ticket

Fixes poster order number margin bottom.

---

src/styles/sponsor.module.scss

**What's broken**
Sponsors without links lost margin bottom after #281 was merged.
Added margin bottom to `IMG`.

A11y focus ring fix sponsor

---

src/components/poster-card/index.module.scss

Ref: https://tipit.avaza.com/project/view/295592#!tab=task-pane&groupby=ProjectSection&view=vertical&task=2849129&fileview=grid

Removes poster card overlay z-index causing overlapping.

---

src/styles/style.scss

**What's wrong**
Skip to content link is kind of small and placed over the logo.
Changed style to make it larger and centered:

Improved style for Skip to content link.

---

src/actions/presentation-actions.js
src/templates/poster-detail-page.js

Until now, when getPresentationById action erred out (either by a getAccessToken error or getRequest error), poster detail page got stuck rendering 'Loading poster'.
This PR fixes that.

Fixes poster detail rendering when poster fetch erred out.

---

src/components/LobbyHeroComponent.js
src/styles/lobby-hero.module.scss

* Removes the middle bar on the lobby header
No
Nothing
ref: https://tipit.avaza.com/project/view/305538#!tab=task-pane&task=2870743

Remove middle diagonal

---

src/styles/lobby-hero.module.scss

* Changes the styles of the lobby header, removing the diagonal containers
No
Nothing
ref: https://tipit.avaza.com/task#!sortby=DateUpdatedDesc&task=2870743

Adjusting header diagonal container

---

src/components/VideoComponent.js
src/components/VideoJSPlayer.js
src/templates/event-page.js

* Get the new start param from streaming_url and passed as prop to video component
* Fix for events without streaming_url
No
Nothing
ref: https://tipit.avaza.com/project/view/232086#!tab=task-pane&task=2888992

Adding start time to video from event streaming url param

---

src/components/Content.js

* Changes the options to keep the `<p>` tags with images and no text
No
Nothing
ref: https://tipit.avaza.com/project/view/305538#!tab=task-pane&task=2891001

Change options in clean-html to render images

---

src/templates/event-page.js
src/templates/home-page.js
src/templates/sponsor-page.js

These PRs https://github.com/fntechgit/virtualevent-poc/pull/372, https://github.com/fntechgit/virtualevent-poc/pull/351 implemented upcoming events widget link render props _only_ on lobby template.
This PR implements those link render props on event detail and sponsor templates.
Also, as a bonus (or eastern egg), the View All link to schedule page now filters by track (if exists) on event detail template and by company on sponsor template.
Ref: https://tipit.avaza.com/project/view/232086#!tab=task-pane&groupby=ProjectSection&view=vertical&task=2892649&fileview=grid

Implements upcoming events widget link render props
